name: Monolith
version: '${version}'
main: org.kouyang07.monolith.Monolith
api-version: '1.20'
load: STARTUP
authors: [Kouyang07]
description: The official plugin for Monolith!
commands:
  ls:
    description: Set player health.
    usage: /ls set [player] [health]
  monocreate:
    description: Gives a custom item to the player.
    usage: /monocreate [itemName]
    aliases: [mc]
  monospawn:
    description: Spawns a custom mob.
    usage: /monospawn [mob]
    aliases: [ms]
  skills:
    description: Open the skills GUI
    usage: /skills
  monorecipe:
    description: Look up recipe for custom items
    usage: /monorecipe [itemName]